"use client";

import { useMemo, useState } from "react";

import type { ClauseFinding } from "../../lib/contracts";
import { useToast } from "../../lib/toast";
import { ConfidenceRing } from "./confidence-ring";

type Props = { findings: ClauseFinding[] };

type RiskKey = "critical" | "high" | "medium" | "low";

const RISK_META: Record<
  RiskKey,
  { glyph: string; pill: string; border: string; quote: string; ringColor: string; aura: string }
> = {
  critical: {
    glyph: "⬣",
    pill: "bg-error-container text-on-error-container",
    border: "border-l-error",
    quote: "border-error/30 bg-error/5",
    ringColor: "#dc2626",
    aura: "aura-critical",
  },
  high: {
    glyph: "▲",
    pill: "bg-orange-100 text-orange-800",
    border: "border-l-status-warn",
    quote: "border-status-warn/30 bg-status-warn/5",
    ringColor: "#ea580c",
    aura: "aura-warn",
  },
  medium: {
    glyph: "◆",
    pill: "bg-blue-100 text-blue-800",
    border: "border-l-status-info",
    quote: "border-status-info/30 bg-status-info/5",
    ringColor: "#2563eb",
    aura: "aura-info",
  },
  low: {
    glyph: "▪",
    pill: "bg-slate-100 text-slate-800",
    border: "border-l-slate-400",
    quote: "border-slate-400/30 bg-slate-50",
    ringColor: "#475569",
    aura: "",
  },
};

export function FindingsList({ findings }: Props) {
  const { push } = useToast();
  const [filter, setFilter] = useState<RiskKey | "all">("all");
  const [selected, setSelected] = useState<string | null>(null);

  async function copyToClipboard(text: string, successMsg: string) {
    try {
      await navigator.clipboard.writeText(text);
      push(successMsg, "success");
    } catch {
      push("Clipboard blocked — copy manually.", "error");
    }
  }

  function generateCounterOffer(f: ClauseFinding) {
    const counter =
      f.safer_language ||
      "Cap each party's aggregate liability at fees paid in the prior 12 months. Carve out indemnity, IP infringement, and breaches of confidentiality.";
    const block = `Counter-offer for "${f.clause_name.replace(/_/g, " ")}":\n\nOriginal:\n${f.excerpt}\n\nProposed replacement:\n${counter}\n\nRationale:\n${f.explanation}`;
    copyToClipboard(block, "Counter-offer copied to clipboard");
  }

  function sendToLawyer(f: ClauseFinding) {
    const subject = encodeURIComponent(
      `Clarifyd: review needed — ${f.clause_name.replace(/_/g, " ")} (${f.risk_level})`
    );
    const body = encodeURIComponent(
      `Hi,\n\nFlagging this clause for your review.\n\nClause: ${f.clause_name.replace(/_/g, " ")}\nRisk level: ${f.risk_level}\nFinding id: ${f.finding_id}\nConfidence: ${Math.round(f.confidence * 100)}%\n\nExcerpt:\n${f.excerpt}\n\nClarifyd analysis:\n${f.explanation}\n\nSuggested safer language:\n${f.safer_language ?? "—"}\n\n(Generated by Clarifyd — not legal advice.)`
    );
    window.location.href = `mailto:?subject=${subject}&body=${body}`;
  }

  const filtered = useMemo(() => {
    const base = findings.filter((f) => f.clause_name !== "uncategorized" && f.risk_level !== "low");
    if (filter === "all") return base;
    return base.filter((f) => f.risk_level === filter);
  }, [filter, findings]);

  const selectedFinding = useMemo(() => {
    const base = filtered.length ? filtered : findings;
    return base.find((f) => f.finding_id === selected) ?? base[0] ?? null;
  }, [filtered, findings, selected]);

  // Group detected clauses by clause type for the reference index.
  const clauseGroups = useMemo(() => {
    const map = new Map<
      string,
      { name: string; count: number; topRisk: RiskKey; firstId: string }
    >();
    const rank: Record<RiskKey, number> = { low: 0, medium: 1, high: 2, critical: 3 };
    for (const f of findings) {
      if (f.clause_name === "uncategorized") continue;
      const key = f.clause_name;
      const risk = (f.risk_level as RiskKey) ?? "low";
      const existing = map.get(key);
      if (!existing) {
        map.set(key, { name: key, count: 1, topRisk: risk, firstId: f.finding_id });
      } else {
        existing.count += 1;
        if (rank[risk] > rank[existing.topRisk]) existing.topRisk = risk;
      }
    }
    return Array.from(map.values()).sort(
      (a, b) => rank[b.topRisk] - rank[a.topRisk] || b.count - a.count
    );
  }, [findings]);

  if (!findings.length) {
    return (
      <section className="crystal-glass rounded-3xl p-8">
        <h2 className="font-display-hero text-h2 text-onboarding-navy mb-2">Risky clauses</h2>
        <p className="text-on-surface-variant">
          No findings yet — upload a contract above to begin.
        </p>
      </section>
    );
  }

  const stats = {
    reviewed: findings.length,
    flagged: filtered.length,
  };

  return (
    <section className="flex flex-col lg:flex-row w-full gap-gutter items-start">
      <aside className="hidden lg:flex flex-col gap-6 w-nav-sidebar-width shrink-0 self-start sticky top-[120px]">
        <div className="crystal-glass rounded-3xl p-6 shadow-md">
          <h3 className="font-h3 text-h3 mb-4">Filters</h3>
          <div className="flex flex-col gap-4">
            <div className="flex flex-col gap-2">
              <span className="font-label-caps text-label-caps text-on-surface-variant">RISK LEVEL</span>
              <div className="flex flex-wrap gap-2">
                {(["all", "critical", "high", "medium", "low"] as const).map((level) => {
                  const active = filter === level;
                  const m = level === "all" ? null : RISK_META[level];
                  const pillBase = m
                    ? m.pill
                    : "bg-white/60 text-on-surface border border-glass-border";
                  return (
                    <button
                      key={level}
                      type="button"
                      onClick={() => setFilter(level)}
                      className={`px-3 py-1 rounded-full text-body-sm font-semibold flex items-center gap-1 cursor-pointer transition-all ${pillBase} ${
                        active ? "ring-2 ring-primary scale-105" : "opacity-80 hover:opacity-100"
                      }`}
                    >
                      {m ? <span>{m.glyph}</span> : null}
                      {level === "all" ? "All" : level[0].toUpperCase() + level.slice(1)}
                    </button>
                  );
                })}
              </div>
            </div>
          </div>
        </div>

        <div className="crystal-glass rounded-3xl p-6 shadow-md">
          <h3 className="font-h3 text-h3 mb-2">Analysis Stats</h3>
          <div className="space-y-3">
            <div className="flex justify-between items-center">
              <span className="text-body-sm">Clauses Reviewed</span>
              <span className="font-bold">{stats.reviewed}</span>
            </div>
            <div className="flex justify-between items-center">
              <span className="text-body-sm">Findings</span>
              <span className="font-bold">{stats.flagged}</span>
            </div>
            <div className="w-full bg-surface-container rounded-full h-2 overflow-hidden">
              <div
                className="bg-primary h-full transition-all"
                style={{
                  width: `${stats.reviewed ? Math.round((stats.flagged / stats.reviewed) * 100) : 0}%`,
                }}
              />
            </div>
          </div>
        </div>
      </aside>

      <section className="flex-grow min-w-0 flex flex-col gap-10 w-full">
        <div>
          <div className="flex items-end gap-3 px-2">
            <span className="font-display-hero text-[80px] md:text-[100px] leading-none text-primary/10 select-none">
              {String(filtered.length).padStart(2, "0")}
            </span>
            <h2 className="font-display-hero text-h1-mobile lg:text-h1 text-onboarding-navy -ml-10 md:-ml-16 pb-2">
              Analysis Findings
            </h2>
          </div>

          {clauseGroups.length ? (
            <div className="px-2 mt-2">
              <span className="font-label-caps text-label-caps text-on-surface-variant uppercase tracking-widest">
                Detected clauses &amp; references
              </span>
              <div className="flex flex-wrap gap-2 mt-3">
                {clauseGroups.map((g) => {
                  const m = RISK_META[g.topRisk] ?? RISK_META.low;
                  return (
                    <button
                      key={g.name}
                      type="button"
                      onClick={() => setSelected(g.firstId)}
                      className="flex items-center gap-2 px-3 py-1.5 rounded-full crystal-glass hover:-translate-y-0.5 transition-transform"
                      title={`Jump to ${g.name.replace(/_/g, " ")}`}
                    >
                      <span
                        className="w-2.5 h-2.5 rounded-full shrink-0"
                        style={{ background: m.ringColor }}
                      />
                      <span className="text-body-sm font-semibold text-on-surface capitalize">
                        {g.name.replace(/_/g, " ")}
                      </span>
                      <span className="text-[10px] font-bold text-on-surface-variant bg-black/5 px-1.5 py-0.5 rounded-full">
                        {g.count}
                      </span>
                    </button>
                  );
                })}
              </div>
            </div>
          ) : null}
        </div>

        {filtered.length === 0 ? (
          <div className="crystal-glass rounded-3xl p-8">
            <p className="text-on-surface-variant">No findings match this filter.</p>
          </div>
        ) : null}

        {filtered.map((f, idx) => {
          const riskKey = (f.risk_level as RiskKey) ?? "low";
          const meta = RISK_META[riskKey] ?? RISK_META.low;
          const injection = f.explanation.startsWith("[injection-suspect]");
          const isSelected = selectedFinding?.finding_id === f.finding_id;
          const score = typeof f.risk_score === "number" ? f.risk_score : null;
          const offset = idx % 2 === 0 ? "offset-left" : "offset-right";
          return (
            <div
              key={f.finding_id}
              role="button"
              tabIndex={0}
              onClick={() => setSelected(f.finding_id)}
              onKeyDown={(e) => {
                if (e.key === "Enter" || e.key === " ") setSelected(f.finding_id);
              }}
              className={`crystal-glass peel-card ${meta.aura} ${offset} rounded-3xl p-6 md:p-8 border-l-[6px] ${meta.border} relative overflow-hidden group cursor-pointer ${
                isSelected ? "ring-2 ring-primary" : ""
              }`}
            >
              <div className="flex justify-between items-start mb-6 gap-3">
                <div className="flex items-start gap-4 min-w-0">
                  <div
                    className="w-12 h-12 shrink-0 rounded-2xl flex items-center justify-center text-2xl font-bold"
                    style={{
                      color: meta.ringColor,
                      background: `${meta.ringColor}1a`,
                    }}
                  >
                    {meta.glyph}
                  </div>
                  <div className="flex flex-col min-w-0">
                    <h3 className="font-display-hero text-h3 lg:text-2xl text-onboarding-navy capitalize leading-tight">
                      {f.clause_name.replace(/_/g, " ")}
                    </h3>
                    <span className="font-label-caps text-label-caps text-on-surface-variant uppercase tracking-widest mt-1">
                      {f.clause_name.replace(/_/g, " ")}
                      {score !== null ? ` • RISK ${(score / 10).toFixed(1)}` : ""}
                    </span>
                  </div>
                </div>
                <div className="flex items-center gap-2 shrink-0">
                  <ConfidenceRing value={f.confidence} color={meta.ringColor} />
                  {injection ? (
                    <span className="bg-error-container text-on-error-container px-3 py-1 rounded-full text-[10px] font-bold uppercase tracking-tight border border-error/20">
                      Injection flagged
                    </span>
                  ) : null}
                </div>
              </div>
              <div
                className={`rounded-2xl p-5 md:p-6 mb-6 border-l-4 ${meta.quote}`}
              >
                <blockquote className="italic font-display-hero text-on-surface-variant text-base md:text-lg leading-relaxed m-0">
                  &ldquo;{f.excerpt}&rdquo;
                </blockquote>
              </div>
              <div className="flex items-center justify-between pt-5 border-t border-white/50 gap-3">
                <p className="text-body-sm text-on-surface/80 leading-relaxed flex-1">
                  {f.explanation}
                </p>
                <span className="material-symbols-outlined text-primary group-hover:translate-x-2 transition-transform shrink-0">
                  arrow_forward_ios
                </span>
              </div>
            </div>
          );
        })}
      </section>

      <aside className="hidden lg:block w-inspector-panel-width shrink-0">
        <div className="sticky top-[120px] crystal-glass rounded-3xl overflow-hidden shadow-2xl">
          <div className="bg-primary p-6 md:p-8 text-white relative overflow-hidden">
            <div className="absolute -right-8 -top-8 w-32 h-32 bg-white/10 rounded-full blur-3xl" />
            <h3 className="font-display-hero text-2xl flex items-center gap-3 m-0 relative z-10">
              <span className="material-symbols-outlined">analytics</span>
              Clause Inspector
            </h3>
            <p className="text-body-sm opacity-80 mt-2 relative z-10">
              Deep AI analysis of risk exposure
            </p>
          </div>
          {selectedFinding ? (
            <div className="p-6 space-y-6">
              <div className="space-y-2">
                <span className="font-label-caps text-label-caps text-on-surface-variant">
                  EXPERT REASONING
                </span>
                <p className="text-body-sm leading-relaxed text-on-surface">
                  {selectedFinding.explanation}
                </p>
              </div>
              <div className="space-y-2">
                <span className="font-label-caps text-label-caps text-on-surface-variant">
                  SUGGESTED REVISION
                </span>
                <div className="bg-surface-container-low p-4 rounded-xl border border-glass-border font-code-snippet text-body-sm italic">
                  {selectedFinding.safer_language ||
                    "Consider adding tighter caps and mutuality to reduce exposure."}
                </div>
              </div>
              <div className="flex flex-col gap-3 pt-4">
                <button
                  type="button"
                  onClick={() => generateCounterOffer(selectedFinding)}
                  className="btn-capsule btn-capsule-primary w-full btn-magnetic"
                >
                  <span className="material-symbols-outlined">auto_fix</span>
                  Draft Counter-Offer
                </button>
                <button
                  type="button"
                  onClick={() => sendToLawyer(selectedFinding)}
                  className="btn-capsule glass-semi-clear w-full text-primary"
                >
                  <span className="material-symbols-outlined">mail</span>
                  Send to Counsel
                </button>
              </div>
            </div>
          ) : (
            <div className="p-6">
              <p className="text-on-surface-variant">Select a clause to view details.</p>
            </div>
          )}
        </div>
      </aside>
    </section>
  );
}
